package com.pam.consultafr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class datos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String abreviado;
	private java.lang.String ap;
	private java.lang.String delito;
	private java.lang.String dnp;
	private java.lang.String region;
	private java.lang.String sd;

	public datos() {
	}

	public java.lang.String getAbreviado() {
		return this.abreviado;
	}

	public void setAbreviado(java.lang.String abreviado) {
		this.abreviado = abreviado;
	}

	public java.lang.String getAp() {
		return this.ap;
	}

	public void setAp(java.lang.String ap) {
		this.ap = ap;
	}

	public java.lang.String getDelito() {
		return this.delito;
	}

	public void setDelito(java.lang.String delito) {
		this.delito = delito;
	}

	public java.lang.String getDnp() {
		return this.dnp;
	}

	public void setDnp(java.lang.String dnp) {
		this.dnp = dnp;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.lang.String getSd() {
		return this.sd;
	}

	public void setSd(java.lang.String sd) {
		this.sd = sd;
	}

	public datos(java.lang.String abreviado, java.lang.String ap,
			java.lang.String delito, java.lang.String dnp,
			java.lang.String region, java.lang.String sd) {
		this.abreviado = abreviado;
		this.ap = ap;
		this.delito = delito;
		this.dnp = dnp;
		this.region = region;
		this.sd = sd;
	}

}