package com.pam.consultafr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class respuestafr implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String response;

	public respuestafr() {
	}

	public java.lang.String getResponse() {
		return this.response;
	}

	public void setResponse(java.lang.String response) {
		this.response = response;
	}

	public respuestafr(java.lang.String response) {
		this.response = response;
	}

}